### ISSUE TITLE
adicionar slides: Táticas de mobilização em torno de um produto de software de participação

### ISSUE THREAD

**Issue by joenio** [lappis-unb/minilappisconf#12]
@ricardopoppi você pode pedir os slides da apresentação da Marcela para adicionar aqui ao repositório? Obrigado!

**Comment by ricardopoppi** [comment]
Em anexo 
[Apresentação_CPA_Táticas_de_Mobilização.pdf](https://github.com/lappis-unb/minilappisconf/files/2103587/Apresentacao_CPA_Taticas_de_Mobilizacao.pdf)
